const path = require('node:path');
const fs = require('node:fs');
const crypto = require('node:crypto');
const express = require('express');
const multer = require('multer');
const XLSX = require('xlsx');
const Database = require('better-sqlite3');

const root = __dirname;
const dataDir = path.join(root, 'data');
const db = new Database(path.join(dataDir, 'jamstock.db'));
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });
const app = express();
const sessions = new Set();
const port = 3000;

fs.mkdirSync(dataDir, { recursive: true });
app.use(express.json({ limit: '2mb' }));
app.use(express.static(path.join(root, 'public'), { setHeaders: (response) => response.setHeader('Cache-Control', 'no-store') }));

db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS participants (id INTEGER PRIMARY KEY AUTOINCREMENT, first_name TEXT NOT NULL, last_name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, experience TEXT, primary_instrument TEXT, other_instruments TEXT, skills TEXT, genres TEXT, availability TEXT, status TEXT NOT NULL DEFAULT 'eligible', checked_in INTEGER NOT NULL DEFAULT 0, raw_json TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bands (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, locked INTEGER NOT NULL DEFAULT 0, generation INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS band_members (band_id INTEGER NOT NULL, participant_id INTEGER NOT NULL, PRIMARY KEY (band_id, participant_id));`);

function hash(value, salt = crypto.randomBytes(16).toString('hex')) { return `${salt}:${crypto.scryptSync(value, salt, 64).toString('hex')}`; }
function verify(value, stored) { const [salt, digest] = stored.split(':'); const candidate = crypto.scryptSync(value, salt, 64).toString('hex'); return crypto.timingSafeEqual(Buffer.from(candidate, 'hex'), Buffer.from(digest, 'hex')); }
function normalize(value) { return String(value || '').trim().toLowerCase().replace(/\s+/g, ' '); }
function requireAuth(request, response, next) { const authorization = request.headers.authorization || ''; const token = authorization.startsWith('Bearer ') ? authorization.slice(7) : authorization || request.query.token; if (!sessions.has(token)) return response.status(401).json({ error: 'Authentication required' }); next(); }
function configured() { return Boolean(db.prepare('SELECT value FROM settings WHERE key = ?').get('password_hash')); }
function value(row, ...names) { for (const name of names) if (row[name] !== undefined) return String(row[name]).trim(); return ''; }
function parseRows(buffer, filename) { const workbook = XLSX.read(buffer, { type: 'buffer' }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; return XLSX.utils.sheet_to_json(sheet, { defval: '' }).map((row) => ({ ...row, source_file: filename })); }
function mentorshipScore(answer) { if (answer.includes('experience that I would love to share')) return 100; if (answer.includes('new and will humbly learn')) return 75; if (answer.includes('not here to learn')) return 0; return 50; }
function displayParticipant(participant) { let raw = {}; try { raw = JSON.parse(participant.raw_json || '{}'); } catch {} const mentorship = value(raw, 'Are you willing to be a humble listener and/or a patient mentor regardless if you are a veteran musician or have ZERO musical background?'); return { ...participant, mentorship, mentorship_score: mentorshipScore(mentorship), instruments: participant.primary_instrument || 'Needs review', secondary_instruments: participant.other_instruments || 'None listed' }; }
function classify(row) { const first = value(row, 'First name'); const last = value(row, 'Last name'); const email = value(row, 'Email'); const ticket = value(row, 'Have you purchased your event ticket?'); const age = value(row, 'Are you 21 or older?'); const transport = value(row, 'Do you have reliable transportation to meet the required in-person portions of the event?', 'Do you have reliable transportation to meet the required in-person portions of the event? *'); const commitment = value(row, 'Are you committed to being a reliable bandmate for the full 48 hours of this event?'); const status = !first || !last || !email ? 'invalid' : ticket !== 'Yes' || age === 'No' || transport === 'No' || commitment.startsWith('I cannot') ? 'excluded' : 'eligible'; return { first_name: first, last_name: last, email: normalize(email), experience: value(row, 'How much music experience do you have?'), primary_instrument: value(row, 'What is your primary instrument? (Check all that apply)'), other_instruments: value(row, 'What other instruments can you play? (Check all that apply)'), skills: value(row, 'What musical skills do you have? (Check all that apply)'), genres: value(row, 'What genres are you most comfortable playing (Check all that apply)'), availability: value(row, 'What hours are you free during the 48-hour event? (Check all that apply)'), status, raw_json: JSON.stringify(row), issue: status === 'eligible' ? '' : status === 'excluded' ? 'Eligibility rule' : 'Missing required field' }; }
// Bands must have 3-6 members; distributes remainders so no group falls outside that range instead of leaving a short leftover chunk.
function bandSizes(total) { if (total < 3) return []; const full = Math.floor(total / 5); const remainder = total % 5; const sizes = Array(full).fill(5); if (remainder === 0) return sizes; if (remainder === 3 || remainder === 4) { sizes.push(remainder); return sizes; } if (remainder === 1) { if (sizes.length) sizes[sizes.length - 1] += 1; else sizes.push(1); return sizes; } if (sizes.length) { sizes[sizes.length - 1] -= 1; sizes.push(3); } else sizes.push(2); return sizes; }

app.get('/api/auth/status', (request, response) => response.json({ configured: configured() }));
app.post('/api/auth/setup', (request, response) => { if (configured()) return response.status(409).json({ error: 'Administrator is already configured.' }); const { password, answers = [] } = request.body; if (!password || password.length < 10 || answers.length !== 3 || answers.some((answer) => !answer.trim())) return response.status(400).json({ error: 'Use a password of at least 10 characters and answer all three recovery questions.' }); db.prepare('INSERT INTO settings (key, value) VALUES (?, ?), (?, ?), (?, ?)').run('password_hash', hash(password), 'answer_1', hash(normalize(answers[0])), 'answer_2', hash(normalize(answers[1]))); db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)').run('answer_3', hash(normalize(answers[2]))); const token = crypto.randomBytes(32).toString('hex'); sessions.add(token); response.json({ token }); });
app.post('/api/auth/login', (request, response) => { const record = db.prepare('SELECT value FROM settings WHERE key = ?').get('password_hash'); if (!record || !verify(request.body.password || '', record.value)) return response.status(401).json({ error: 'Incorrect password.' }); const token = crypto.randomBytes(32).toString('hex'); sessions.add(token); response.json({ token }); });
app.post('/api/auth/reset', (request, response) => { const { password, answers = [] } = request.body; const records = [1, 2, 3].map((number) => db.prepare('SELECT value FROM settings WHERE key = ?').get(`answer_${number}`)); if (!configured() || !password || password.length < 10 || answers.length !== 3 || answers.some((answer) => !answer.trim()) || records.some((record, index) => !record || !verify(normalize(answers[index]), record.value))) return response.status(401).json({ error: 'The recovery answers did not match.' }); db.prepare('UPDATE settings SET value = ? WHERE key = ?').run(hash(password), 'password_hash'); const token = crypto.randomBytes(32).toString('hex'); sessions.add(token); response.json({ token }); });
app.post('/api/auth/logout', (request, response) => { sessions.delete(request.headers.authorization); response.json({ ok: true }); });

app.get('/api/dashboard', requireAuth, (request, response) => { const participants = db.prepare('SELECT * FROM participants ORDER BY last_name, first_name').all().map(displayParticipant); const bands = db.prepare('SELECT * FROM bands ORDER BY id').all(); const members = db.prepare('SELECT bm.band_id, p.* FROM band_members bm JOIN participants p ON p.id = bm.participant_id').all().map(displayParticipant); const bandDetails = bands.map((band) => ({ ...band, members: members.filter((member) => member.band_id === band.id) })); response.json({ eligible: participants.filter((person) => person.status === 'eligible').length, checkedIn: participants.filter((person) => person.checked_in).length, issues: participants.filter((person) => person.status !== 'eligible').length, bands: bands.length, participants, bandDetails }); });
app.post('/api/participants/:id/check-in', requireAuth, (request, response) => { db.prepare('UPDATE participants SET checked_in = CASE checked_in WHEN 1 THEN 0 ELSE 1 END WHERE id = ?').run(request.params.id); response.json({ ok: true }); });
app.post('/api/participants/check-in-all', requireAuth, (request, response) => { const result = db.prepare("UPDATE participants SET checked_in = 1 WHERE status = 'eligible'").run(); response.json({ ok: true, count: result.changes }); });

app.post('/api/import/preview', requireAuth, upload.single('file'), (request, response) => { if (!request.file) return response.status(400).json({ error: 'Choose a CSV or Excel file.' }); const rows = parseRows(request.file.buffer, request.file.originalname).map(classify); const emails = new Set(); let duplicates = 0; for (const row of rows) { if (row.email && emails.has(row.email)) { row.status = 'duplicate'; duplicates += 1; } else if (row.email) emails.add(row.email); } response.json({ rows, valid: rows.filter((row) => row.status === 'eligible').length, excluded: rows.filter((row) => row.status === 'excluded').length, invalid: rows.filter((row) => row.status !== 'eligible').length, duplicates }); });
app.post('/api/import/commit', requireAuth, (request, response) => { const insert = db.prepare('INSERT OR IGNORE INTO participants (first_name,last_name,email,experience,primary_instrument,other_instruments,skills,genres,availability,status,raw_json) VALUES (@first_name,@last_name,@email,@experience,@primary_instrument,@other_instruments,@skills,@genres,@availability,@status,@raw_json)'); let inserted = 0; let duplicates = 0; const save = db.transaction((rows) => rows.filter((row) => row.status === 'eligible').forEach((row) => { const result = insert.run(row); if (result.changes) inserted += 1; else duplicates += 1; })); save(request.body); response.json({ ok: true, inserted, duplicates }); });

app.post('/api/bands/generate', requireAuth, (request, response) => { const people = db.prepare("SELECT * FROM participants WHERE status = 'eligible' AND checked_in = 1 ORDER BY id").all(); if (people.length < 3) return response.status(400).json({ error: 'Check in at least three eligible participants first.' }); const locked = db.prepare('SELECT id FROM bands WHERE locked = 1').all().map((band) => band.id); if (!locked.length) db.prepare('DELETE FROM bands').run(); const generation = (db.prepare('SELECT COALESCE(MAX(generation), 0) + 1 AS next FROM bands').get().next); const createBand = db.prepare('INSERT INTO bands (name, generation) VALUES (?, ?)'); const addMember = db.prepare('INSERT INTO band_members (band_id, participant_id) VALUES (?, ?)'); const save = db.transaction(() => { const available = people.filter((person) => !db.prepare('SELECT 1 FROM band_members WHERE participant_id = ? AND band_id IN (SELECT id FROM bands WHERE locked = 1)').get(person.id)); const sizes = bandSizes(available.length); let offset = 0; sizes.forEach((size, index) => { const band = createBand.run(`Band ${locked.length + index + 1}`, generation); available.slice(offset, offset + size).forEach((person) => addMember.run(band.lastInsertRowid, person.id)); offset += size; }); }); save(); response.json({ ok: true, message: `Draft generated from ${people.length} checked-in participants.` }); });
app.post('/api/bands/clear', requireAuth, (request, response) => { const save = db.transaction(() => { db.prepare('DELETE FROM band_members').run(); db.prepare('DELETE FROM bands').run(); }); save(); response.json({ ok: true }); });
app.post('/api/bands/:id/lock', requireAuth, (request, response) => { db.prepare('UPDATE bands SET locked = CASE locked WHEN 1 THEN 0 ELSE 1 END WHERE id = ?').run(request.params.id); response.json({ ok: true }); });
app.get('/api/bands/export', requireAuth, (request, response) => { const bands = db.prepare('SELECT * FROM bands ORDER BY id').all(); const members = db.prepare('SELECT bm.band_id, p.first_name, p.last_name, p.email, p.primary_instrument, p.other_instruments FROM band_members bm JOIN participants p ON p.id = bm.participant_id ORDER BY bm.band_id').all(); const escape = (value) => `"${String(value ?? '').replace(/"/g, '""')}"`; const rows = [['Band', 'Status', 'First name', 'Last name', 'Email', 'Primary instrument', 'Other instruments']]; bands.forEach((band) => { const bandMembers = members.filter((member) => member.band_id === band.id); if (!bandMembers.length) rows.push([band.name, band.locked ? 'Locked' : 'Draft', '', '', '', '', '']); bandMembers.forEach((member) => rows.push([band.name, band.locked ? 'Locked' : 'Draft', member.first_name, member.last_name, member.email, member.primary_instrument, member.other_instruments])); }); const csv = rows.map((row) => row.map(escape).join(',')).join('\n'); response.setHeader('Content-Type', 'text/csv'); response.setHeader('Content-Disposition', 'attachment; filename="jamstock-bands.csv"'); response.send(csv); });

app.post('/api/reset', requireAuth, (request, response) => { const save = db.transaction(() => { db.prepare('DELETE FROM band_members').run(); db.prepare('DELETE FROM bands').run(); db.prepare('DELETE FROM participants').run(); }); save(); response.json({ ok: true }); });

app.use('/api', (request, response) => response.status(404).json({ error: `API route not found: ${request.method} ${request.path}` }));

app.listen(port, '127.0.0.1', () => console.log(`RVA JamStock running at http://localhost:${port}`));
